# This dockefile will setup a container with pytorch lightning and all the dependencies

ARG PYTHON_VERSION=3.10
ARG CUDA_VERSION=11.2

FROM nvcr.io/nvidia/rapidsai/rapidsai:23.02-cuda${CUDA_VERSION}-runtime-ubuntu20.04-py${PYTHON_VERSION}