name: Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linter:
    name: Linters
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: pip install -e '.[linting]'
    - name: Lint with flake8
      run: flake8 nerf/ --select=F,E112,E113,E304,E502,E702,E703,E71,E72,E731,W191,W6 --statistics -j4
    - name: Lint with pylint
      run: pylint nerf/
    - name: Run mypy
      run: mypy nerf/ test/ --ignore-missing-imports
